# Generated by Django 4.1.7 on 2023-08-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_userprofile_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('worker', 'Worker')], default='', max_length=10),
        ),
    ]
