# Generated by Django 4.1.7 on 2023-08-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('worker', 'Worker'), ('recruiter', 'Recruiter')], default='None', max_length=10),
        ),
    ]
