# Generated by Django 4.2.4 on 2023-08-12 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('main_text', models.TextField(max_length=1700)),
                ('company_name', models.CharField(max_length=25)),
                ('years_of_experience', models.IntegerField(help_text='Max 10 years of experience', validators=[django.core.validators.MaxValueValidator(10)])),
                ('category', models.CharField(choices=[('PHP', 'PHP Back-end developer'), ('Python QA', 'Python Automation QA'), ('Python BE', 'Python Back-end developer'), ('C/C++ Emb', 'C/C++ Embedded'), ('JS Front', 'JavaScript/Front-end'), ('JS Back', 'Node.js')], max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('application_filed', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('english_level', models.CharField(blank=True, choices=[('A0/A1', 'Beginner/Elementary'), ('A2', 'Pre Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficient')], max_length=20)),
                ('salary', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('geolocation', models.CharField(blank=True, max_length=20)),
                ('company_site', models.URLField(blank=True)),
            ],
        ),
    ]
