# Generated by Django 4.2.4 on 2023-08-12 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Max 10 years of experience', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
