# Generated by Django 4.1.7 on 2023-08-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_alter_vacancy_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='main_text',
            field=models.TextField(max_length=2500),
        ),
    ]
