# Generated by Django 4.1.7 on 2023-08-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_response_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='response',
            name='vacancy',
            field=models.ManyToManyField(null=True, to='vacancy.vacancy'),
        ),
    ]
