# Generated by Django 4.1.7 on 2023-08-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_remove_response_vacancy_response_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='vacancy',
            field=models.ManyToManyField(to='vacancy.vacancy'),
        ),
    ]
