# Generated by Django 4.1.7 on 2023-08-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_alter_response_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='response',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy'),
        ),
    ]
